#! /bin/sh

NAME=influxd
PIDFILE=/var/run/$NAME.pid

case "$1" in
  start)
    printf "Starting $NAME: "
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --startas /usr/bin/influxd
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    printf "Stopping $NAME: "
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  restart|reload)
    echo "Restarting $NAME: "
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}" >&2
    exit 1
    ;;
esac

exit 0